### ISSUE TITLE
Blank page on Chrome with a basic Susy grid

### ISSUE THREAD

**Issue by gioele** [oddbird/susy#106]
This simple page + scss comes up as a blank page in Chrome 18+ on Linux; works fine with Firefox and IE.

The page should show the Susy grid background and a yellow block of content.

Test `style.scss` file:

``` scss
$total-columns  : 16;
$column-width   : 80%;
$gutter-width   : 20%;
$grid-padding   : 0;

$container-width: 100%;
$container-style: fluid;

@import "susy";

html {
    @include container;
    @include susy-grid-background;
}

#content {
    @include push(11);
    @include span-columns(4);
}

h1 {
    font-size: 200%;
    font-weight: bold;
    margin-bottom: 1em;
}

#content {
    padding: 2em;
    background-color: yellow;
}
```

Testcase HTML file:

``` html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>A simple test</title>
    <meta charset='utf-8' />
    <link href='style.css' rel='stylesheet' type='text/css' />
  </head>
  <body>
    <div id='main'>
      <div id='content'>
        <h1 id="a-simple-test">A simple test</h1>
        <p>This should occupy 4 columns out of 16, starting from the 11th column.</p>
      </div>
    </div>
  </body>
</html>
```
