### ISSUE TITLE
Consider adding span-columns-base mixin

### ISSUE THREAD

**Issue by sidonath** [oddbird/susy#111]
Hi and thanks for Susy!

Sometimes I need to create an irregular column, ie. column with width and margin that don't match the grid settings.

With Blueprint/Compass I would `@include column-base` and then set width/margin manually. There doesn't seem to be a similar base mixin in Susy.

My use-case is that I want to create a side-nav which connects to the main content, so I don't need right margin. Something like this:

``` scss
.side-nav {
  @include span-columns(0);
  width: space(6);
  margin-right: 0;
}
```

The only problem here is that this generates redundant width and margin-right statements, thus bloating output a bit:

``` css
.side-nav {
  width: 0%;
  float: left;
  margin-right: 1.05263%;
  display: inline;
  width: 25.26316%;
  margin-right: 0;
}

Ideally there would be `span-columns-base` mixin which would float the element to the left and take care about IE6 support.
```
