### ISSUE TITLE
Include loop with nth-omega

### ISSUE THREAD

**Issue by Anahkiasen** [oddbird/susy#124]
I have the following mixin :

``` scss
// Define a number of items per row -------------------------------- /

=perRow($perRow, $numberColumns: $total-columns, $padding: false, $last: false)
  $span: $numberColumns / $perRow
  +span-columns($span, $numberColumns, $padding)
  @if $last
    +nth-omega
  @else
    +nth-omega(#{$perRow}n, of-type)
```

When I use it I get the following error, which I don't understand :

```
(Line 173 of _grid.scss: An @include loop has been found:
    perRow includes nth-omega
    nth-omega includes adjust-support-for)
```

Everything works fine until cbf7291987f57b13850d1ebc1caee5f46a3b99e7, after that it doesn't work.
