### ISSUE TITLE
Issue with IE fallback output order

### ISSUE THREAD

**Issue by paulyoung** [oddbird/susy#153]
In my app I'm using the IE fallback option in conjunction with modernizr to target all devices which don't support media queries.

Among other things, my configuration looks like this:

``` Scss
$total-columns: 12;
$column-width: 60px;
$gutter-width: 20px;
$grid-padding: 20px;

$border-box-sizing: true;

$bp1-columns: 9;
$bp2-columns: $total-columns;

$bp1: $bp1-columns no-mediaqueries;
$bp2: $bp2-columns no-mediaqueries;
```

I'm taking a mobile-first approach, so I'm adding the class to both breakpoint one and breakpoint two so that a rule I define in breakpoint one will also be applied at breakpoint two and on devices without media query support.

My issue is that the order I define things in scss affects the order of the compiled css. For example:

``` Scss
// Four items in a row
@include at-breakpoint($bp2) {
  @include remove-nth-omega(3n);
  @include span-columns(3, $bp2-columns);
  @include nth-omega(4n);
}

// Three items in a row
@include at-breakpoint($bp1) {
  @include nth-omega(3n);
  @include span-columns(3, $bp1-columns);
}
```

Outputs:

``` Css
/* Four items in a row */
.no-mediaqueries .module-reward.small {
  width: 23.40426%;
  float: left;
  margin-right: 2.12766%;
  display: inline; }

/* Three items in a row */
.no-mediaqueries .module-reward.small {
  width: 31.42857%;
  float: left;
  margin-right: 2.85714%;
  display: inline; }
```

This is not the desired result. I would expect that rules for breakpoint two would always appear after rules for breakpoint one, no matter what order they were defined.

At the moment I don't think this is a problem for me since I usually define rules in ascending order of breakpoint, but it would be good know that it's not an issue if I didn't do that.
