### ISSUE TITLE
Avoid units for 0 values

### ISSUE THREAD

**Issue by rpkoller** [oddbird/susy#199]
Something i've noticed while checking my CSS output with CSSlint. Would it make sense to leave out units for zero values? So far i've found it in the output of the isolate-grid function (example attached beneath - margin-left: 0%),  but i don't know if there are any further functions with an similar output behaviour in Susy. Best regards Ralf

``` scss
.overview{ 
    li{
    @include isolate-grid(6,18);
    }
}
```

``` css
.overview li {
  width: 32.39437%;
  float: left;
  margin-right: 1.40845%;
  margin-right: -100%;
}
.overview li:nth-child(3n + 1) {
    margin-left: 0%;
    clear: left; 
}
.overview li:nth-child(3n + 2) {
    margin-left: 33.80282%;
    clear: none;
}
  .overview li:nth-child(3n + 3) {
    margin-left: 67.60563%;
    clear: none;
}
```
