### ISSUE TITLE
"Last" not working as expected

### ISSUE THREAD

**Issue by imnikkilee** [oddbird/susy#309]
I'm making the switch from Susy One to Susy Two and while creating a basic sample grid to get a feel for the new syntax, I've come across a problem with how "last" (or "omega") works. 

This is how my initial code looked. Notice I'm using "nth-child" to select the last element in the grid. 

HTML:

``` HTML
<div class="show-grid-container">
    <div class="show-grid-col"></div>
    <div class="show-grid-col"></div>
    <div class="show-grid-col"></div>
    <div class="show-grid-col"></div>
</div>
```

SCSS:

``` CSS
.show-grid-container {

    @include layout(4 1em);

    .show-grid-col {
        @include span(1);
        background: green;
        min-height: 100px;

        &:nth-child(4n) {
            @include span(last 1);
            background: green;
            min-height: 100px;
        }
    }
}
```

However, this doesn't work because using "last" doesn't get rid of the margin-right that the original "span(1)" adds. 

If I change my code to the following it works as desired: 

HTML:

``` HTML
<div class="show-grid-container">
    <div class="show-grid-col"></div>
    <div class="show-grid-col"></div>
    <div class="show-grid-col"></div>
    <div class="show-grid-col-last"></div>
</div>
```

SCSS:

``` CSS
.show-grid-container {

    @include layout(4 1em);

    .show-grid-col {
        @include span(1);
        background: green;
        min-height: 100px;
    }

    .show-grid-col-last {
        @include span(last 1);
        background: green;
        min-height: 100px;
    }
}
```

However, my HTML is going to be dynamic and so it's necessary that I'm able to use "nth-child" to select the last elements in the grid. I found a way to get around this for now by adding "(gutter-override: 0)" to "span(last 1)" but I think it'd be a good addition if you were able to make "span(last)" work in a way that supported nth-children automatically, maybe by automatically adding a "margin-right:0"? I'd appreciate your thoughts on this. Hope I explained myself well enough. Thanks a bunch!
