### ISSUE TITLE
duplicate declarations with omega

### ISSUE THREAD

**Issue by pdewouters** [oddbird/susy#32]
am I doing something wrong?

this:

``` scss
        .footer-widgets-2{
            @include columns(6,12);
            @include omega;
        }
```

results in this:

``` css
  #footer-widgets .footer-widgets-2 {
    display: inline;
    float: left;
    width: 48.75%;
    margin-right: 2.5%;
    display: inline;
    float: right;
    margin-right: 0%;
    #margin-left: -24px;
  }
```

is there any way to avoid the duplicate float and display declartions?
