### ISSUE TITLE
baseline grid image invisible with small $base-line-height values

### ISSUE THREAD

**Issue by ju1ius** [oddbird/susy#354]
Hi,

For flexibility, I often like to define a `$base-line-height` that's a fraction of the `$base-font-size`, for example:

``` scss
@import "compass/typography/vertical_rhythm";
$base-font-size: 18px;
$base-line-height: 6px;
@include establish-baseline();

html {
    // line-height: 1.3333em
    @include adjust-leading-to(4);
}
p {
    // margin-bottom: 1em
    margin-bottom: rhythm(3);
}
```

With this setting however, the baseline grid background gradient becomes invisible (the same bug exists in compass). I think that it's because the gradient color stops are defined in percentages and cause the browser to round the values to zero.
Replacing the output by the following in the style inspector fixes this bug:

``` css
.container {
    background-image: linear-gradient(
        to bottom,
        rgba(0, 0, 0, 0.5) 1px,
        rgba(0, 0, 0, 0) 1px
    );
}
```
