### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by atom2ueki** [oddbird/susy#473]
![screen shot 2015-05-03 at 11 36 31 am](https://cloud.githubusercontent.com/assets/5100535/7443565/c10b2eea-f188-11e4-8687-8b52d5a217e8.png)
I found that what ever how you setup Susy, even in youtube/web tutorial, when open debug image, there is always a little gap there in the right-hand side, but when you slowly resize the browser, it will disappeared, and come again like a loop, is it caused by the gutter setting? because the ratio cannot be divided into integer

**Comment by ericam** [comment]
Yes, this is a known browser bug in handling sub-pixel rounding on background-images as [noted in the documentation](susydocs.oddbird.net/en/latest/toolkit/#show-grid). This is why we are considering an svg alternative in #440.

**Comment by signalwerk** [comment]
In chrome it's kind of unpleasant to debug. I used the following code to draw the grid for the whole 100% and then it looks perfect:

```SCSS
$susy: (
  columns: 7,
  gutters: 1/6,
  math: fluid,
  output: float,
);

@mixin grid-column-gradient($values...) {
  background-image: linear-gradient(to right, #{$values});
}


@function gradient-stops($grid-columns) {
  $transparent: rgba(0,0,0,0);
  $color: rgba(0,0,0,0.07);

  $column-offset: 0;

  $values: ($color 0);

  @for $i from 1 through $grid-columns {

    @if $i != $grid-columns  {
      $column-offset: $column-offset + span(1);
      $values: append($values, $color $column-offset, comma);
      $values: append($values, $transparent $column-offset, comma);
      $column-offset: $column-offset + gutter();
      $values: append($values, $transparent $column-offset, comma);
      $values: append($values, $color $column-offset, comma);
    } @else {
      $column-offset: $column-offset + span(1);
      $values: append($values, $color $column-offset, comma);
      $values: append($values, $transparent $column-offset, comma);
    }
  }

  @return $values;
}


.container {
	/* mark */
	@include grid-column-gradient(gradient-stops(7));
}

```

Based on that code:
[_visual-grid.scss](https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_visual-grid.scss)
