### ISSUE TITLE
Getting wrong math with gallery() and libSass 3.3.2

### ISSUE THREAD

**Issue by kmuncie** [oddbird/susy#549]
Having an issue with the math when using gallery(). The following reduced test case will demonstrate what I am seeing. 

Test code 

```css
.test {
  @include gallery(3 of 12, $selector: of-type);
}
```

Expected output (seen in sassmeister.com running libSass 3.2.5)
```css
.test {
  width: 23.72881%;
  float: left;
}

.test:nth-of-type(4n + 1) {
  margin-left: 0;
  margin-right: -100%;
  clear: both;
  margin-left: 0;
}

.test:nth-of-type(4n + 2) {
  margin-left: 25.42373%;
  margin-right: -100%;
  clear: none;
}

.test:nth-of-type(4n + 3) {
  margin-left: 50.84746%;
  margin-right: -100%;
  clear: none;
}

.test:nth-of-type(4n + 4) {
  margin-left: 76.27119%;
  margin-right: -100%;
  clear: none;
}
```

Output seen from grunt-sass 1.1.0 which is running node-sass 3.4.2 and libSass 3.3.2
```css
.test {
  width: 25%;
  float: left;
 }

.test:nth-of-type(4n + 1) {
    margin-left: 0;
    margin-right: -100%;
    clear: both;
    margin-left: 0; 
}

.test:nth-of-type(4n + 2) {
    margin-left: 25%;
    margin-right: -100%;
    clear: none; 
}

.test:nth-of-type(4n + 3) {
    margin-left: 50%;
    margin-right: -100%;
    clear: none; 
}

.test:nth-of-type(4n + 4) {
    margin-left: 75%;
    margin-right: -100%;
    clear: none; 
}
```

**Can anyone reproduce this? Seems to be a rounding issue on the surface.**
