### ISSUE TITLE
Getting rid of float left ?

### ISSUE THREAD

**Issue by FrederiqueGame** [oddbird/susy#557]
Hello dear Eric !
A+1 for Susy I've just began to approach.
I just wonder how it's possible to not have a float left on my code, because with the default setting of Susy, we have it engraved ;)

And after compilling sass files, css file delevers a line for each propriety with this float (example above) which would not be necessary on a mobile structure.
I personnally declare my styles for mobile and then, my breakpoints > desktop and more which inherit...
(and float right is not possible, so ?)

Thanks a lot for your answer :)

```scss
@media (min-width: 40em) {
  .content-area {
    width: 100%;
    float: left;
    padding-left: 1.25%;
    padding-right: 1.25%;
    background: orange;
  }
}
@media (min-width: 60em) {
  .content-area {
    width: 75%;
    float: left;
    padding-left: 0.8333333333%;
    padding-right: 0.8333333333%;
    background: red;
  }

  .site-content .widget-area {
    width: 25%;
    float: left;
    padding-left: 0.8333333333%;
    padding-right: 0.8333333333%;
  }
}
```

**Comment by mirisuzanne** [comment]
Hi @FrederiqueGame -

Wherever possible, I use the least intrusive mixin, or even functions. For example, anywhere you want `width: 100%` for mobile, you can skip the Susy span mixin entirely - `100%` is the browser default for block elements. In your first media-query above, the gutters are the only useful output, so I'd use the `gutter` mixin instead:

```scss
@media (min-width: 40em) {
  .content-area {
    @include gutters();
    background: orange;
  }
}
```

There is also a `span` function, and a `gutter` function, which let you get only the properties you actually want, e.g.:

```scss
.example {
  width: span(3); // span 3 columns
  margin-left: span(2); // push it 2 columns
  padding: 0 gutter(); // add gutter padding
}
```
