### ISSUE TITLE
Status V3

### ISSUE THREAD

**Issue by mmjaeger** [oddbird/susy#583]
hello
was wondering what the status of V3 is - any flex box support yet?

Thanks

**Comment by mirisuzanne** [comment]
v3 is not far from a beta release, but it's hard to estimate any date - that's the nature of open source.

v2 already works great with flexbox. There is no reason to build a mixin around it, like we did for floats. We don't see good way to improve on the css syntax, but you can align flex-items to the grid using our `span()` and `gutter()` functions:

```scss
.item {
  flex: 1 1 span(2);
  margin-right: gutter();
}
```

That will still be true in v3.
