### ISSUE TITLE
Can't set flow in mixin?

### ISSUE THREAD

**Issue by rogerrogers** [oddbird/susy#590]
Should I be able to do this?

```
@mixin rtl {
    $susy: (flow: rtl);
    body[dir="rtl"] {
      @content;
    }
}
```

I can't get this mixin to work. The Susy flow direction isn't changed for the output. I assume this means the $susy variables aren't being processed again within the mixin. 

I'm trying to achieve something like what is suggested here: http://stackoverflow.com/questions/18337816/susy-responsive-grids-for-compass-text-direction/18341273#18341273

**Comment by mirisuzanne** [comment]
Global variables aren't scoped that way. You have to override the global value, and then reset it at the end of your mixin. Something like this:

```scss
    $susy: (flow: rtl) !global;
    body[dir="rtl"] & {
      @content;
    }
    $susy: (flow: ltr) !global;
}
```

**Comment by rogerrogers** [comment]
Thanks @mirisuzanne! That did the trick.

With the site I am working on, basically everything must be both RTL and LTR. The mixin I created was basically the @include bi mixin that I referenced in the link earlier (also provided by @mirisuzanne).

The problem is that it feels like this is generating a LOT of duplicate .css if I'm wrapping large blocks of sass with this mixin, or is really kludgy if I'm wrapping each relevant include in context. 

So, I wonder if there is some way of extending the susy mixins like @include span to be more like @include span-bi(). Or better yet, just a way to make susy output both rtl and ltr flows using some defined selector (e.g. html[dir="rtl"]). 

Not sure if this makes any sense?

Thanks again @mirisuzanne.

**Comment by mirisuzanne** [comment]
I wouldn't use a new mixin at all. If you want to flip the entire site left/right, I'd compile two different style sheets, using partials so you don't have to duplicate. The trick is that you have to replace any mention of `left` or `right` in your partials. Instead, you can use Susy's `to()` and `from()` functions.

```scss
// _partial.scss
.example {
  @include span(3);
  border-#{to()}: 1px solid #000;
}

// ltr.scss
$susy: ('flow': 'ltr');
@include 'partial';

// rtl.scss
$susy: ('flow': 'rtl');
@include 'partial';
```

There would be clever ways to hide those functions, but I'll leave that as a separate exercise. :)
