### ISSUE TITLE
rem fallback on susy3

### ISSUE THREAD

**Issue by robsonsobral** [oddbird/susy#606]
Hi!

Please, how can I set a `rem` fallback on Susy3?

I have:

```sass
$gutter: (30 / 16 * 1rem);

$susy: (
	'columns': 12 x (70 / 16 * 1rem),
	'gutters': $gutter,
);


@mixin central{
	max-width: susy-span(12);
	padding: 0 $gutter/1rem*16px;
	padding: 0 $gutter;
	margin: 0 auto;
}
```

How can I set a fallback for `max-width`?

Thank you for your attention.

**Comment by mirisuzanne** [comment]
I imagine you could use the exact same approach, right? 

```scss
max-width: susy-span(12) / 1rem * 16px;
```

If you'll be doing that a lot, you might want a rem-fallback function and/or mixin. Something like these:

```scss
@function rem-to-px($rem, $root: 16px) {
  @return $rem / 1rem * $root;
}

@mixin rem-fallback($property, $value, $root: 16px) {
  @if type-of($value) == 'number' and unit($value) == 'rem' {
    #{$property}: rem-to-px($value, $root);
  }
  
  #{$property}: $value;
}

@mixin central{
    @include rem-fallback('max-width', susy-span(12));
    padding: 0 rem-to-px($gutter);
    padding: 0 $gutter;
    margin: 0 auto;
}
```
