### ISSUE TITLE
Negative margins in container are off ever so slightly

### ISSUE THREAD

**Issue by mrcsmcln** [oddbird/susy#616]
In essence, I'm trying to break out of a nested grid item to achieve the original parent width. Here's a simple example using `split` gutters:

```html
<div class="parent">
    <div class="child"></div>
</div>
```

```scss
.parent {
    @include gutters; // 3.3333%
}

.child {
    // Does not sit flush over .parent
    margin-right: -(gutter()); // -3.3333%
    margin-left: -(gutter()); // -3.3333%
}
```

Of course, the above code does not calculate the child gutters to the exact width of the parent gutters because the child is nested and Susy's `gutter()` function has no way of knowing that it's supposed to be negative or that the child is nested.

But I get the same result if I try using the `nested()` mixin:

```scss
.parent {
    @include gutters; // 3.3333%
}

.child {
    @include nested(12) {
        // Still does not sit flush over .parent
        margin-right: -(gutter()); // -3.3333%
        margin-left: -(gutter()); // -3.3333%
    }
}
```

Which also makes sense to me to a degree. That being said, I'm unable to find a pixel-perfect solution to this problem. Basically, I want to be able to nest grid items and restore the original parent width in the grid item.

Is this at all possible, or is it required that grid items expecting children should be rendered as `wide no-gutters` and then leave the gutter work to the children? Please let me know if clarification is required.

**Comment by mirisuzanne** [comment]
Yeah, that's a really difficult calculation, and not something you can easily express in Susy. It would be a bit simpler with 3.0 where you can individually set the child and parent `spread` values, but that doesn't help you. 

The `wide no-gutters` solution is definitely the best for simplicity, if that works for your needs, because it doesn't require any special math, or negated gutters. I think the [`nest` keyword](http://susydocs.oddbird.net/en/latest/toolkit/#nesting) (on the parent) should do the same thing, since it defines it as a nesting context...

You can also do the more complex math. Written simply, you need `$target-width / $context-width * 100%`. I think [this is working for me](http://codepen.io/mirisuzanne/pen/5e4a67a5a43e79779ef461de4b5304ec?editors=1100#0), but I haven't done extensive tests...

```scss
// using `after` to get the combined gutter-width
$context: 100% - gutter('after');
$target: gutter();
$negative-gutter: -($target / $context * 100%);

.parent {
  @include gutters;
}

.child {
  margin-left: $negative-gutter; 
  margin-right: $negative-gutter; 
}
```
