### ISSUE TITLE
Error in plugin 'sass' ...seems to be scss file line 1 no matter what

### ISSUE THREAD

**Issue by hellofantastic** [oddbird/susy#626]
Hello ladies and gentlemen,

I seek your insight.

I am in the process of getting setup with Susy 2 / sass in a node.js/angular setup using gulp via following along on a  @zellwk  tutorial.

I have latest gulp, gulp-sass and normalize-scss installed through npm. 

I have been testing using gulp sass command in terminal

My first error was regarding not being able to find "normalize" so I updated the gulpfile and added a path for includePaths to normalize scss folder. 

That error went away and next error was:
```
Error in plugin 'sass'
Message:
    src/scss/base.scss
Error: Properties are only allowed within rules, directives, mixin includes, or other properties.
        on line 1 of src/scss/base.scss
>> @import "normalize";
   ^
22:09:41] Finished 'sass' after 237 ms
```
 which led me to go through a bunch of dead ends in different github repos issues for gulp-sass, node-sass, libsass.

Then I tried added a comment at the top of this base.scss "//Base" because I see it a top many sample scss files and get the same error but for the comment:
```
[22:32:05] Starting 'sass'...
Error in plugin 'sass'
Message:
    src/scss/base.scss
Error: Properties are only allowed within rules, directives, mixin includes, or other properties.
        on line 1 of src/scss/base.scss
>> //Base
   ^
[22:32:05] Finished 'sass' after 182 ms
```
Here is my gulpfile

```javascript
var gulp = require('gulp');
var sass = require('gulp-sass');

//Sass 
gulp.task('sass', function() {
  return gulp.src('src/scss/*.scss')
      .pipe(sass({
          outputStyle: 'compressed',
          includePaths: ['node_modules/susy/sass','node_modules/normalize-scss/sass']
      }).on('error', sass.logError))
      .pipe(gulp.dest('public/assets/css'));
});
```

base.scss:

```scss
//Base
@import "normalize";
@import "susy";

$susy: (
    columns: 12,  // The number of columns in your grid
    gutters: 1/4, // The size of a gutter in relation to a single column
    global-box-sizing: border-box
);
@include border-box-sizing;

// The Container Mixin
@include container( 75em );

```

Any insight , anything else I can provide?

**Comment by hellofantastic** [comment]
Further investigation, if I turn my scss into this:

```css
//Base
.test{
    width: percentage(5/7);
}
```

**Comment by mirisuzanne** [comment]
I'm not sure exactly what the question is. If you are asking about how gulp-sass reports errors, and why it is saying "line 1" — that's a question for their github channel, not something we control on our end. 

But I do see the likely cause of your error. The `container` mixin, should be applied to a selector. It will output raw property/value pairs, which are not allowed at the root of the document. The proper use would be something like this:

```scss
//Base
@import "normalize";
@import "susy";

$susy: (
    columns: 12,  // The number of columns in your grid
    gutters: 1/4, // The size of a gutter in relation to a single column
    global-box-sizing: border-box
);
@include border-box-sizing;

// The Container Mixin
.container {
  @include container( 75em );
}
```

Notice the selector around `@include container`. Hope that helps!
