### ISSUE TITLE
Grid breaking in Firefox.

### ISSUE THREAD

**Issue by jeremypeters** [oddbird/susy#63]
This issue only seems to affect Firefox(12.0), Chrome is OK. I've only just started playing with Susy though, so it's quite possible there is something I've overlooked.

I have a a full-width ul, and below 6 columns width I want each li to be full-width; at 8 columns I would like 2 to a row; and at 12 columns, 3 to a row. Everything works as expected, except when the window is between 945px - 960px wide, where the 3rd li drops down breaking the grid. Dropping the width of every third li by 1% realigns the li's to the grid to the position they should be in.

Hope that all makes sense. Here is my broken down code.

HTML:

``` html
...blah...
<container>
    ...blah...
    <ul>
        <li>blah</li>
        <li>blah</li>
        <li>blah</li>
        <li>blah</li>
        <li>blah</li>
        <li>blah</li>
        <li>blah</li>
        ...etc...   
    </ul>
    ...blah...
</container>
...blah...
```

SCSS:

``` scss
$base-font-size: 14px;

$total-columns  : 4;           
$column-width   : 4em;           
$gutter-width   : 1.5em;           
$grid-padding   : $gutter-width; 

$break-1 : 6;
$break-2 : 8;
$break-3 : 12;  

.container{
    @include container($total-columns,$break-1,$break-2,$break-3);
}

ul{
    list-style-type:none;
    padding:0;
    @include pie-clearfix;
}

li{
    float:left;
    @include span-columns(4, 4);
}

@include at-breakpoint($break-1) {
    li{
        @include span-columns(6, 6);
    }   
}

@include at-breakpoint($break-2) {
    li{
        @include span-columns(4, 8);
        &:nth-child(2n+2){@include omega;}
    }   
}

@include at-breakpoint($break-3) {
    li{
        @include span-columns(4, 12);
        // need to add this in here, because the $omega settings are inherited from previous media query
        &:nth-child(2n+2){float:left;margin-right:$gutter-width;}
        &:nth-child(3n+3){@include omega;}
    }   
}
```

Many thanks,

Jez
