### ISSUE TITLE
Change grid settings based on responsive breakpoints in Susy 3

### ISSUE THREAD

**Issue by davidchameleon** [oddbird/susy#658]
Hello,
I would really appreciate some suggestions when it comes to using Susy 3 to implement a series of fixed pixel grid layouts, which change according to media query break points. 

For example, let's say you have the following settings for an old school 960px grid:

```
$susy: (
  'columns': susy-repeat(12, 60px),
  'gutters': 20px,
  'spread': 'narrow',
  'container-spread': 'wide', 
);
```
But at a certain break point, you want to switch to different settings, for example a 720px grid with 10 columns as opposed to 12:

```
$susyTablet: (
  'columns': susy-repeat(10, 52px),
  'gutters': 20px,
  'spread': 'narrow',
  'container-spread': 'wide', 
);
```

What would you recommend as being the best, and most efficient way to do this with Susy 3?

**Comment by mirisuzanne** [comment]
Hi David - we've been getting this question a lot, so I decided to answer you with a blog post. I've created two snippets that will help, and I explain a bit about how to use them – or make changes to match the syntax you prefer. There's a [draft PR on github](https://github.com/oddbird/oddsite/pull/141), or the post will go live in a day or two. Here are th snippets…

This one wraps a block of Sass, using the new global settings:
```scss
  @mixin susy-use(
    $settings
  ) {
    //  parse and normalize any shorthand arguments
    $settings: susy-compile($settings);

    // record the global settings -
    // and update the global variable with our new settings
    $global: $susy;
    $susy: map-merge($susy, $settings) !global;

    // any content inside this mixin
    // will use the local settings
    @content;

    // return the global variable to its initial value
    $susy: $global !global;
  }
```

And this one works the same, but includes media-query logic directly to your settings maps:

```scss
  @mixin susy-at(
    $settings
  ) {
    //  parse and normalize any shorthand arguments
    $settings: susy-compile($settings);

    // build min-and-max queries
    $min: map-get($settings, 'min-width');
    $min: if($min, '(min-width: #{$min})', null);
    $max: map-get($settings, 'max-width');
    $max: if($max, '(max-width: #{$max})', null);

    // combine them if we need both
    $and: if($min and $max, '#{$min} and #{$max}', null);
    // or fall back to the value we need…
    $query: $and or $min or $max;

    // apply the results…
    @media #{$query} {
      @include susy-use($settings) {
        @content;
      }
    }
  }
```

Use either one by passing in settings as an argument, and then nesting content inside the mixin block:

```scss
@media (min-width: 30em) {
  @include susy-use($medium) {
    /* this code will use the $medium map of susy settings */
  }
}

@include susy-at($medium) {
  /* this code will use the $medium map of susy settings,
      with a media-query also documented in the map e.g. `'min-width': 30em` */
}
```
