### ISSUE TITLE
set different global Gutter base on media querie

### ISSUE THREAD

**Issue by HectorLS** [oddbird/susy#675]
hello,
 i have search a similar issue of how to set different gutter base on media querie.

But i still dont get it 😞
[Susy sample on Codepen](https://codepen.io/HectorLeon/pen/vjKzqB)

```scss
$susy: (
  'columns': susy-repeat(12),
  'gutters': 10px,
  'spread': 'narrow',
  'container-spread': 'narrow',
  'svg-grid-colors': hsl(180, 50%, 80%)
);


@media (min-width: 1440px) {

  $susy: (
    'columns': susy-repeat(12),
    'gutters': 30px,   // Increase the gutter when 1440px
    'spread': 'narrow',
    'container-spread': 'narrow',
    'svg-grid-colors': hsl(180, 50%, 80%)
  );
}

```
This is a sample case i just created, what i want to achieve is just increase the gutter between columns at certain media querie.

set a susy map variable for mobile width and another one for desktop for example.
Can you help me with this ? 🙏 i'm not being able to override the susy map
