### ISSUE TITLE
@if index($span, 'last') {

### ISSUE THREAD

**Issue by jvandenrym** [oddbird/susy#683]
I have created a gist with susy 3 and a span mixin.
https://gist.github.com/jvandenrym/64070b3cc0920ba7752bd2b495ca3ab1

The checking of the last item does not do anything. Not sure I can even use this expression.
`@if index($span, 'last') {`

**Comment by mirisuzanne** [comment]
Yeah, `if index($span, 'last')` relies on the user explicitly adding `last` to the span argument. A more robust approach would probably look like this:

```scss
$is-last: (map-get($context, 'span') + map-get($context, 'location') - 1) == map-get($context, 'columns');
@if $is-last { … }
```
